In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('FOOD-DATA-GROUP1.csv')

In [3]:
data.head()

,Unnamed: 0.1,Unnamed: 0,food,Caloric Value,Fat,Saturated Fats,Monounsaturated Fats,Polyunsaturated Fats,Carbohydrates,Sugars,...,Calcium,Copper,Iron,Magnesium,Manganese,Phosphorus,Potassium,Selenium,Zinc,Nutrition Density
0,0,0,cream cheese,51,5.0,2.9,1.3,0.200,0.8,0.500,...,0.008,14.100,0.082,0.027,1.300,0.091,15.5,19.100,0.039,7.070
1,1,1,neufchatel cheese,215,19.4,10.9,4.9,0.800,3.1,2.700,...,99.500,0.034,0.100,8.500,0.088,117.300,129.2,0.054,0.700,130.100
2,2,2,requeijao cremoso light catupiry,49,3.6,2.3,0.9,0.000,0.9,3.400,...,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.000,5.400
3,3,3,ricotta cheese,30,2.0,1.3,0.5,0.002,1.5,0.091,...,0.097,41.200,0.097,0.096,4.000,0.024,30.8,43.800,0.035,5.196
4,4,4,cream cheese low fat,30,2.3,1.4,0.6,0.042,1.2,0.900,...,22.200,0.072,0.008,1.200,0.098,22.800,37.1,0.034,0.053,27.007

In [5]:
data.describe()

,Unnamed: 0.1,Unnamed: 0,Caloric Value,Fat,Saturated Fats,Monounsaturated Fats,Polyunsaturated Fats,Carbohydrates,Sugars,Protein,...,Calcium,Copper,Iron,Magnesium,Manganese,Phosphorus,Potassium,Selenium,Zinc,Nutrition Density
count,551.000000,551.000000,551.000000,551.000000,551.000000,551.000000,551.000000,551.000000,551.000000,551.000000,...,551.000000,551.000000,551.000000,551.000000,551.000000,551.000000,551.000000,551.000000,551.000000,551.000000
mean,275.000000,275.000000,237.359347,10.766933,3.722715,4.001564,2.170793,15.819036,2.708907,18.417857,...,94.848290,8.579102,1.530819,34.549289,3.537002,219.735563,347.234483,35.009212,1.652964,144.663207
std,159.204271,159.204271,199.235598,12.544196,5.397021,5.540608,3.470820,20.289320,7.455666,18.932404,...,170.568662,44.379145,1.883603,45.296399,12.595878,243.550965,380.140492,153.034744,6.519636,187.047623
min,0.000000,0.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.025000
25%,137.500000,137.500000,94.500000,2.500000,0.500000,0.600000,0.400000,0.000000,0.000000,5.300000,...,9.650000,0.049000,0.300000,6.500000,0.048000,50.250000,90.000000,0.021000,0.300000,39.933500
50%,275.000000,275.000000,186.000000,6.600000,1.800000,2.200000,1.100000,5.100000,0.000000,11.900000,...,38.300000,0.100000,1.000000,21.100000,0.100000,134.100000,223.200000,0.050000,0.800000,84.100000
75%,412.500000,412.500000,337.000000,14.400000,4.800000,5.150000,2.600000,28.700000,2.200000,25.650000,...,101.400000,0.300000,2.200000,47.100000,0.500000,317.450000,456.100000,0.084000,1.700000,170.691500
max,550.000000,550.000000,1578.000000,87.500000,43.500000,48.000000,40.100000,128.300000,70.800000,86.900000,...,1283.500000,668.600000,21.100000,376.200000,111.600000,1385.100000,3198.400000,1679.000000,147.300000,1337.000000

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 551 entries, 0 to 550
Data columns (total 37 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0.1          551 non-null    int64
 1   Unnamed: 0            551 non-null    int64
 2   food                  551 non-null    object
 3   Caloric Value         551 non-null    int64
 4   Fat                   551 non-null    float64
 5   Saturated Fats        551 non-null    float64
 6   Monounsaturated Fats  551 non-null    float64
 7   Polyunsaturated Fats  551 non-null    float64
 8   Carbohydrates         551 non-null    float64
 9   Sugars                551 non-null    float64
 10  Protein               551 non-null    float64
 11  Dietary Fiber         551 non-null    float64
 12  Cholesterol           551 non-null    float64
 13  Sodium                551 non-null    float64
 14  Water                 551 non-null    float64
 15  Vitamin A             551 non-null    float64
 16  Vitamin B1            551 non-null    float64
 17  Vitamin B11           551 non-null    float64
 18  Vitamin B12           551 non-null    float64
 19  Vitamin B2            551 non-null    float64
 20  Vitamin B3            551 non-null    float64
 21  Vitamin B5            551 non-null    float64
 22  Vitamin B6            551 non-null    float64
 23  Vitamin C             551 non-null    float64
 24  Vitamin D             551 non-null    float64
 25  Vitamin E             551 non-null    float64
 26  Vitamin K             551 non-null    float64
 27  Calcium               551 non-null    float64
 28  Copper                551 non-null    float64
 29  Iron                  551 non-null    float64
 30  Magnesium             551 non-null    float64
 31  Manganese             551 non-null    float64
 32  Phosphorus            551 non-null    float64
 33  Potassium             551 non-null    float64
 34  Selenium              551 non-null    float64
 35  Zinc                  551 non-null    float64
 36  Nutrition Density     551 non-null    float64
dtypes: float64(33), int64(3), object(1)
memory usage: 159.4+ KB

In [8]:
# Dropping unnecessary columns
data_cleaned = data.drop(columns=['Unnamed: 0', 'Unnamed: 0.1'])

data_cleaned.head()

,food,Caloric Value,Fat,Saturated Fats,Monounsaturated Fats,Polyunsaturated Fats,Carbohydrates,Sugars,Protein,Dietary Fiber,...,Calcium,Copper,Iron,Magnesium,Manganese,Phosphorus,Potassium,Selenium,Zinc,Nutrition Density
0,cream cheese,51,5.0,2.9,1.3,0.200,0.8,0.500,0.9,0.0,...,0.008,14.100,0.082,0.027,1.300,0.091,15.5,19.100,0.039,7.070
1,neufchatel cheese,215,19.4,10.9,4.9,0.800,3.1,2.700,7.8,0.0,...,99.500,0.034,0.100,8.500,0.088,117.300,129.2,0.054,0.700,130.100
2,requeijao cremoso light catupiry,49,3.6,2.3,0.9,0.000,0.9,3.400,0.8,0.1,...,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.000,5.400
3,ricotta cheese,30,2.0,1.3,0.5,0.002,1.5,0.091,1.5,0.0,...,0.097,41.200,0.097,0.096,4.000,0.024,30.8,43.800,0.035,5.196
4,cream cheese low fat,30,2.3,1.4,0.6,0.042,1.2,0.900,1.2,0.0,...,22.200,0.072,0.008,1.200,0.098,22.800,37.1,0.034,0.053,27.007

In [9]:
# Selecting relevant features for recommendation
features = data_cleaned[['Caloric Value', 'Fat', 'Carbohydrates', 'Protein', 'Sugars', 'Dietary Fiber']]

# Normalize the features
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
features_scaled = scaler.fit_transform(features)

In [10]:
from sklearn.neighbors import NearestNeighbors

# Building the Nearest Neighbors model
model = NearestNeighbors(n_neighbors=5, algorithm='ball_tree')
model.fit(features_scaled)

# Function to get recommendations
def recommend_diet(user_input):
    # Normalize user input
    user_input_scaled = scaler.transform([user_input])
    
    # Find the nearest neighbors
    distances, indices = model.kneighbors(user_input_scaled)
    
    # Get the recommended foods
    recommended_foods = data_cleaned.iloc[indices[0]]
    
    return recommended_foods

# Example user input [Calories, Fat, Carbohydrates, Protein, Sugars, Dietary Fiber]
user_input = [250, 10, 30, 15, 5, 10]

# Get recommendations
recommendations = recommend_diet(user_input)
print(recommendations)

                        food  Caloric Value   Fat  Saturated Fats  \
188  chili with beans canned            287  14.1             6.0
180            bean ham soup            198   2.5             0.6
103          chili con carne            271   8.8             3.2
122        refried red beans            336  16.1             2.2
143              baked beans            310  10.3             3.9

     Monounsaturated Fats  Polyunsaturated Fats  Carbohydrates  Sugars  \
188                   6.0                   0.9           30.5     3.0
180                   1.0                   0.7           33.5     7.8
103                   3.6                   1.0           33.1     4.7
122                   3.9                  10.2           36.0     0.0
143                   4.3                   1.5           43.3     0.0

     Protein  Dietary Fiber  ...  Calcium  Copper  Iron  Magnesium  Manganese  \
188     14.6           11.3  ...  120.300     0.3   8.8      115.2        0.3
180     10.3            9.8  ...   93.100     0.2   2.5       46.6        0.6
103     14.7            8.3  ...    0.063    83.5   0.6        3.4       70.8
122     11.7           11.0  ...   76.900     0.5   4.5       83.9        0.7
143     11.1           11.0  ...    0.000   122.0   0.3        4.0       86.0

     Phosphorus  Potassium  Selenium   Zinc  Nutrition Density
188       394.2      934.4     0.018  5.100            204.000
180        31.9      387.1     0.021  1.300            154.400
103         0.4      220.1   667.900  0.039             66.245
122       212.0      722.3     0.058  1.600            156.200
143         0.5      218.0   716.000  0.052             76.200

[5 rows x 35 columns]

C:\Users\khushi garg\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(